---
- name: Main | Include preflight tasks
  include_tasks: preflight.yml

- name: Main | Include system tasks
  include_tasks: system.yml

- name: Main | Include Firewall tasks
  include_tasks: firewall.yml



