---
- name: Main | Include preflight tasks
  ansible.builtin.include_tasks: preflight.yml

- name: Main | Include system tasks
  ansible.builtin.include_tasks: system.yml

- name: Main | Include Firewall tasks
  ansible.builtin.include_tasks:
    file: firewall.yml
    apply:
      tags:
        - firewall
  tags:
    - firewall
