---
- name: Preflight | Check required input variables
  ansible.builtin.assert:
    that:
      - POOL | default(False)
    fail_msg:
      - "ERROR: POOL ('{{ POOL }}') is not defined"

- name: Preflight | Check system parameters
  ansible.builtin.assert:
    that:
      - (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 11 ) or
        ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 16 )
    fail_msg:
      - "ERROR: Unsupported operating system."
