---
- name: Rocketpool Config | Setup config directories
  file:
    state: directory
    path: "{{ configdir.path }}"
    owner: "{{ configdir.user }}"
    group: "{{ configdir.group }}"
    mode: "{{ configdir.mode }}"
  loop:
    - { 'path': "{{ rocketpool_user_home }}/.rocketpool/data/validators", 'user': "{{ rocketpool.user }}", 'group': "{{ rocketpool.user }}", 'mode': '0755' }
    - { 'path': "{{ prometheus.data_path }}/var/lib/grafana/dashboards", 'user': "nobody", 'group': "nogroup", 'mode': '0755' }
    - { 'path': "/var/lib/node_exporter/textfile_collector", 'user': "root", 'group': "root", 'mode': '0755' }
    - { 'path': "{{ grafana.data_path }}", 'user': "{{ rocketpool.user }}", 'group': "{{ rocketpool.user }}", 'mode': '0775' }
  loop_control:
    label: "{{ configdir.path }}"
    loop_var: "configdir"

- name: Rocketpool Config | Copy rocketpool scripts
  copy:
    src: '{{ static_file.src }}'
    dest: "{{ static_file.dst }}"
    owner: "{{ rocketpool.user }}"
    group: "{{ rocketpool.user }}"
    mode: "{{ static_file.mode | default('0755') }}"
  loop:
    - { 'dst': "{{ rocketpool_user_home }}/.rocketpool/prune_geth.sh" , 'src': 'prune_geth.sh' }
    - { 'dst': "/usr/share/rp-version-check.sh" , 'src': 'rp-version-check.sh' }
    - { 'dst': "/usr/share/apt-metrics.sh" , 'src': 'apt-metrics.sh' }
    - { 'dst': "/etc/apt/apt.conf.d/60prometheus-metrics" , 'src': 'apt-prometheus-metrics', 'mode': '0644' }
    - { 'dst': "{{ prometheus.data_path }}/var/lib/grafana/dashboards/node-exporter-dashboard.json" , 'src': 'node-exporter-dashboard.json', 'mode': '0666' }
    - { 'dst': "{{ prometheus.data_path }}/var/lib/grafana/dashboards/rocketpool-prysm-dashboard.json" , 'src': 'rocketpool-prysm-dashboard.json', 'mode': '0666' }
    - { 'dst': "{{ rocketpool_user_home }}/.rocketpool/grafana-dashboards.yml", 'src': 'grafana-dashboards.yml', 'mode': '0644' }
  loop_control:
    loop_var: 'static_file'
    label: "{{ static_file.dst }}"
