---
- name: Rocketpool Post Install | Check ETH1 port
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: "{{ rocketpool.ports.executionCommonP2pPort }}"
    timeout: 300
    delay: 2

- name: Rocketpool Post Install | Check ETH2 port
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: "{{ rocketpool.ports.consensusCommonP2pPort }}"
    timeout: 300
    delay: 2

- name: Rocketpool Post Install | Check metrics ports
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: "{{ metrics_port }}"
    timeout: 300
    delay: 2
  when: (rocketpool.config | selectattr('name', 'equalto', 'enableMetrics') | selectattr('value', 'in', ('false', 'False', 'FALSE')) | list | count) < 1
  loop:
    - "{{ grafana.port }}"
    - "{{ prometheus.node_exporter.port }}"
    - "{{ prometheus.port }}"
  loop_control:
    loop_var: 'metrics_port'
