---
- name: Rocketpool Post Install | Check ETH1 port
  wait_for:
    host: 0.0.0.0
    port: "{{ rocketpool.ports.gethP2pPort }}"
    timeout: 300
    delay: 2

- name: Rocketpool Post Install | Check ETH2 port
  wait_for:
    host: 0.0.0.0
    port: "{{ rocketpool.ports.consensusCommonP2pPort }}"
    timeout: 300
    delay: 2

- name: Rocketpool Post Install | Check prometheus port if exposed
  wait_for:
    host: 0.0.0.0
    port: "{{ prometheus.port }}"
    timeout: 300
    delay: 2
  when: configOpt.name == 'prometheus-openPort'
  loop: "{{ rocketpool.config }}"
  loop_control:
    label: "{{ configOpt.name }}"
    loop_var: 'configOpt'

- name: Rocketpool Post Install | Check metrics ports
  wait_for:
    host: 0.0.0.0
    port: "{{ metrics_port }}"
    timeout: 300
    delay: 2
  loop:
    - "{{ grafana.port }}"
    - "{{ prometheus.node_exporter.port }}"
  loop_control:
    loop_var: 'metrics_port'
