---
- name: Rocketpool Post Install | Check open ports
  wait_for:
    host: 0.0.0.0
    port: "{{ port }}"
    timeout: 300
    delay: 15
  loop:
    - "{{ grafana.port }}"
    - "{{ eth.eth1.port }}"
    - "{{ eth.eth2.port }}"
    - "{{ prometheus.node_exporter.port }}"
  loop_control:
    loop_var: 'port'
