---
default_packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - acl
  - curl
  - moreutils
  - chrony
  - htop

system:
  # This percentage value controls the tendency of the kernel to reclaim the memory which is used for caching of directory and inode objects.
  # https://sysctl-explorer.net/vm/vfs_cache_pressure/
  vfs_cache_pressure: 10
  vm_swappiness: 1
