---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars_files:
    - "{{ playbook_dir }}/../vars/defaults.yaml"
    - "{{ playbook_dir }}/../vars/pools/{{ POOL }}/node.yaml"
    - "{{ playbook_dir }}/../vars/pools/{{ POOL }}/rocketpool.yaml"
  tasks:
    - name: Playbook | Execute rocketpool role
      ansible.builtin.include_role:
        name: rocketpool
        apply:
          tags:
            - rocketpool

  post_tasks:
    - name: Playbook | Set reboot required fact
      ansible.builtin.stat:
        path: '/var/run/reboot-required'
        get_checksum: false
        get_attributes: false
        get_mime: false
      register: reboot_required

    - name: Playbook | Reboot node if required
      ansible.builtin.reboot:
        msg: "cloudstruct-rocketpool: Reboot required for system package updates."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 120
        post_reboot_delay: 30
        test_command: uptime
      when:
        - reboot_required.stat.exists
        - node.unattended_automatic_reboot
      tags: ['skipci', 'reboot']
