---
- name: Setup System Playbook
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars_files:
    - "{{ playbook_dir }}/../vars/defaults.yaml"
    - "{{ playbook_dir }}/../vars/pools/{{ POOL }}/node.yaml"
    - "{{ playbook_dir }}/../vars/pools/{{ POOL }}/rocketpool.yaml"
  pre_tasks:
    - name: "Rocketpool Main | Set rocketpool_arch fact"
      ansible.builtin.set_fact:
        rocketpool_arch: "{{
          'amd64' if ansible_architecture == 'x86_64'
          else 'arm64' if ansible_architecture == 'aarch64'
          else 'UNSUPPORTED_ARCHITECTURE'
        }}"
        rocketpool_version: "{{ VERSION | default(rocketpool.version) }}"
      tags: ['always']

  tasks:
    - name: Playbook | Include base role
      ansible.builtin.include_role:
        name: base
        apply:
          tags:
            - base
      tags:
        - always

    - name: Playbook | Include jnv.unattended-upgrades role
      ansible.builtin.include_role:
        name: jnv.unattended-upgrades
        apply:
          tags:
            - upgrades
      vars:
        unattended_remove_unused_dependencies: "{{ node.unattended_remove_unused_dependencies | default(true) }}"
        unattended_automatic_reboot: "{{ node.unattended_automatic_reboot }}"
        unattended_automatic_reboot_time: "{{ node.unattended_automatic_reboot_time | default('02:00') }}"
      tags:
        - upgrades

    - name: Playbook | Include dev-sec.ssh-hardening role
      ansible.builtin.include_role:
        name: dev-sec.ssh-hardening
        apply:
          tags:
            - ssh
      tags:
        - ssh

    - name: Playbook | Include dev-sec.os-hardening
      ansible.builtin.include_role:
        name: dev-sec.os-hardening
        apply:
          tags:
            - security
      vars:
        sysctl_overwrite:
          # Enable IPv4 traffic forwarding. Required by Docker.
          net.ipv4.ip_forward: 1
      tags:
        - skipci
        - security

    - name: Playbook | Include geerlingguy.docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_apt_arch: "{{ rocketpool_arch }}"
        docker_compose_arch: "{{ ansible_architecture }}"
        docker_compose_version: "v{{ node.docker.compose.version | default(node.docker.compose.version) }}"
        docker_users: "{{ node.docker.users | default(node.docker.users) | default(['rp']) }}"
        docker_daemon_options: "{{ node.docker.daemon_options }}"
