name: Ansible-Tests

env:
  ANSIBLE_ROLES_PATH: "~/.ansible/roles:/etc/ansible/roles"
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ansible-tests.yml'
      - 'ansible/**'
      - 'vars/**'

defaults:
  run:
    shell: bash
    working-directory: ansible

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pool:
          - mainnet-00
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64

      - uses: actions/cache@v2
        name: Cache dir
        id: cache-python
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ matrix.pool }}-${{ env.pythonLocation }}-${{ hashFiles('requirements_dev.txt') }}

      - name: Install Python dependencies
        id: python-pip-install
        run: |
          python -m pip install --upgrade pip
          pip install -r ${GITHUB_WORKSPACE}/requirements_dev.txt
        if: steps.cache-python.outputs.cache-hit != 'true'

      - uses: actions/cache@v2
        name: Cache dir
        id: cache-ansible
        with:
          path: "~/.ansible"
          key: ${{ matrix.pool }}-ansible-${{ hashFiles('**/requirements.yml') }}

      - name: Install Ansible-Galaxy dependencies
        id: ansible-galaxy-install
        run: ansible-galaxy install -r requirements.yml

      - name: Lint Ansible Playbook
        id: ansible-lint
        run: ansible-lint -vv --exclude ~/.ansible site.yml

      - name: Run playbook
        id: ansible-playbook
        run: ansible-playbook site.yml -e "POOL=mainnet-00" --skip-tags 'skipci' -vvv
